---
# tasks file for cgroup-configuration
 - name: cgroup configuration
   lineinfile:
     path: "/etc/containerd/config.toml"
     regexp: "^\\s*SystemdCgroup\\s*=\\s*false"
     line: "SystemdCgroup = true"
 
 - name: reload daemon
   systemd: 
   daemon_reload: yes

 - name: restart containerd service 
   systemd:
     name: containerd
     state: restarted 

