---
# tasks file for k8sinstall
  - name: load kernel modules
    shell: "modprobe br_netfilter overlay"

  - name: modify /etc/sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      regexp: "^#net.ipv4.ip_forward="
      line: "net.ipv4.ip_forward=1"
      backup: yes

  - name: apt
    apt:
      update_cache: yes

  - name: installing dependencies 
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - conntrack
      update_cache: yes
      state: present 

  - name: download kubernetes gpg key
    geturl: 
      url: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key" 
      dest: "/tmp/kubernetes-apt-keyring.gpg"

  - name: Install kubernetes gpg key
    copy:
      src: "/tmp/kubernetes-apt-keyring.gpg"
      dest: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
      mode: "0644"
      remote_src: yes

  - name: Remove temporary GPG key file
    file:
      path: "/tmp/kubernetes-apt-keyring.gpg"
      state: absent
  
  - name: Add Kubernetes repository line
    lineinfile:
      path: "/etc/apt/sources.list.d/kubernetes.list"
      line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
      create: yes

  - name: install kubelet,kubeadm,kubectl
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present 
      update_cache: yes
      force_apt_get: yes

  - name: Hold kubelet, kubeadm, and kubectl
    command: apt-mark hold {{ item }}
    loop:
      - kubelet
      - kubeadm
      - kubectl
